from __future__ import annotations

import os
from collections.abc import Callable, Iterable
from importlib import import_module
from typing import Protocol, TypeVar

from .models import ProviderConfigurationError

T = TypeVar("T")


class Snapshot(Protocol):
    id: str
    exists: bool
    reference: Document
    def to_dict(self) -> dict | None: ...


class Document(Protocol):
    def get(self, transaction=None) -> Snapshot: ...
    def set(self, data: dict, merge: bool = False) -> None: ...
    def update(self, fields: dict) -> None: ...
    def create(self, data: dict) -> None: ...
    def delete(self) -> None: ...
    def collection(self, name: str) -> Collection: ...
    def collections(self) -> Iterable[Collection]: ...


class Collection(Protocol):
    id: str
    def document(self, document_id: str | None = None) -> Document: ...
    def stream(self) -> Iterable[Snapshot]: ...


class WriteBatch(Protocol):
    def set(self, ref: Document, data: dict, merge: bool = False) -> None: ...
    def update(self, ref: Document, fields: dict) -> None: ...
    def delete(self, ref: Document) -> None: ...
    def commit(self) -> None: ...


class DocumentStore(Protocol):
    def collection(self, name: str) -> Collection: ...
    def batch(self) -> WriteBatch: ...
    def transaction(self) -> WriteBatch: ...


class StorageAdapter(Protocol):
    def client(self) -> DocumentStore: ...
    def equal(self, collection: Collection, field: str, value: str) -> Iterable[Snapshot]: ...
    def transact(self, transaction: WriteBatch, operation: Callable[[WriteBatch], T]) -> T: ...
    def create_once(self, document: Document, data: dict) -> bool: ...


def get_storage_adapter() -> StorageAdapter:
    provider = os.getenv("RECOUP_STORAGE_PROVIDER", "firestore").strip().lower()
    if provider == "firestore":
        return import_module(".google_storage", __package__).FirestoreAdapter()
    raise ProviderConfigurationError(f"Unsupported RECOUP_STORAGE_PROVIDER: {provider}")
